### 포스트작성

POST http://localhost:8080/api/v1/post
Content-Type: application/json
Accept-Encoding: UTF-8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VybmFtZSIsImlhdCI6MTY3MTM0ODYzMiwiZXhwIjoxNjc3Mzk2NjMyfQ.wQnBi0CdyFZzE7hHn3DCcKPyoSu9yJea_-EcyPR2ku0

{
    "title":"testTitle",
    "content":"testContent"
}

### 포스트조회

GET http://localhost:8080/api/v1/post/1
Content-Type: application/json
Accept-Encoding: UTF-8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VybmFtZSIsImlhdCI6MTY3MTM0ODYzMiwiZXhwIjoxNjc3Mzk2NjMyfQ.wQnBi0CdyFZzE7hHn3DCcKPyoSu9yJea_-EcyPR2ku0

### 포스트수정

PUT  http://localhost:8080/api/v1/post/1
Content-Type: application/json
Accept-Encoding: UTF-8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VybmFtZSIsImlhdCI6MTY3MTM0ODYzMiwiZXhwIjoxNjc3Mzk2NjMyfQ.wQnBi0CdyFZzE7hHn3DCcKPyoSu9yJea_-EcyPR2ku0

{
    "title":"testTitle_Modify",
    "content":"testContent_Modify"
}


### 포스팅 삭제

DELETE   http://localhost:8080/api/v1/post/1
Content-Type: application/json
Accept-Encoding: UTF-8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VybmFtZSIsImlhdCI6MTY3MTM0ODYzMiwiZXhwIjoxNjc3Mzk2NjMyfQ.wQnBi0CdyFZzE7hHn3DCcKPyoSu9yJea_-EcyPR2ku0