version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=LOCAL_DB
      - MYSQL_USER=LOCAL_USER
      - MYSQL_PASSWORD=LOCAL_PASSWORD
      - MYSQL_ROOT_PASSWORD=LOCAL_PASSWORD
      - TZ=ASIA/SEOUL
    ports:
      - "3306:3306"
    volumes:
      - /db/conf.d:/etc/mysql/conf.d
      - /db/initdb.d:/docker-entrypoint-initdb.d

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379