### 회원가입
POST http://localhost:8080/api/user/signup
Content-Type: application/json

{
    "username":"test_username",
    "password":"test_password",
    "email":"test_email",
    "memo":"test_memo"
}

### 로그인
POST http://localhost:8080/api/user/login
Content-Type: application/json

{
    "username":"test_username",
    "password":"test_password"
}

### 회원정보 수정
PUT http://localhost:8080/api/user/modify
Content-Type: application/json
Authorization: Bearer [jwt]

{
    "password":"test_password",
    "email":"changed_email",
    "memo":"changed_memo"
}


### 게시글 작성
POST http://localhost:8080/api/article
Content-Type: application/json
Authorization: Bearer [jwt]

{
    "title":"test_title",
    "content":"test_content",
    "hashtags":["test_h1", "test_h2", "test_h3"]
}

### 게시글 수정
PUT http://localhost:8080/api/article
Content-Type: application/json
Authorization: Bearer [jwt]

{
    "articleId":1,
    "title":"modified_title",
    "content":"modified_content",
    "hashtags":["modified_h1", "test_h2", "test_h3"]
}

### 게시글 삭제
DELETE  http://localhost:8080/api/article/1
Content-Type: application/json
Authorization: Bearer [jwt]

### 게시글 다건 조회
GET http://localhost:8080/api/article
Content-Type: application/json
Authorization: Bearer [jwt]

### 게시글 단건 조회
GET http://localhost:8080/api/article/2
Content-Type: application/json
