debug: false

logging:
  level:
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/LOCAL_DB
    username: LOCAL_USER
    password: LOCAL_PASSWORD
  jpa:
    defer-datasource-initialize: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    show-sql: true
    sql-init-mode: always
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  redis:
    host: redis
    port: 6379
    ttl:  # 캐싱 기간 (단위 : day)
      principal: 3


jwt:
  secret-key: JWT_SECRET_KEY_NEED_TO_CHANGE_AT_PRODUCTION
  expire-ms: 1000000